#!/bin/sh
set -eu

case "$(basename "$0")" in
    mise)
        [ "${1:-}" = activate ] && [ "${2:-}" = nu ]
        printf 'export-env { $env.MISE_FIXTURE = "%s" }\n' "${NU_FIXTURE_VERSION:?}"
        ;;
    starship)
        [ "${1:-}" = init ] && [ "${2:-}" = nu ]
        printf 'export-env { $env.STARSHIP_FIXTURE = "%s" }\n' "${NU_FIXTURE_VERSION:?}"
        ;;
    fnox)
        [ "${1:-}" = activate ] && [ "${2:-}" = nu ]
        printf 'def --env fnox [] { "fnox-%s" }\n' "${NU_FIXTURE_VERSION:?}"
        ;;
    wt)
        [ "${1:-}" = config ] && [ "${2:-}" = shell ] && [ "${3:-}" = init ] && [ "${4:-}" = nu ]
        printf 'def --env wt [] { "wt-%s" }\n' "${NU_FIXTURE_VERSION:?}"
        ;;
    *)
        exit 1
        ;;
esac
