[tools]
gh = "latest"
"aqua:eza-community/eza" = { version = "latest", os = ["linux"] }
"conda:eza" = { version = "latest", os = ["macos"] }
fzf = "latest"
fnox = "latest"
helix = "latest"
gitui = "latest"
git-lfs = "latest"
jaq = "latest"
pitchfork = "latest"
starship = "latest"
vivid = "latest"
cargo-binstall = "latest"
delta = "latest"
"aqua:reemus-dev/gitnr" = { version = "latest", os = ["macos"] }
"aqua:BurntSushi/ripgrep" = "latest"
"github:max-sixty/worktrunk" = "latest"
"github:openai/symphony" = { version = "latest", bin = "symphony" }

[tools."github:MitMaro/git-interactive-rebase-tool"]
version = "latest"
[tools."github:MitMaro/git-interactive-rebase-tool".platforms]
macos-arm64 = { asset_pattern = "git-interactive-rebase-tool-*-macos-*_arm" }
macos-x64 = { asset_pattern = "git-interactive-rebase-tool-*-macos-*_intel" }
linux-x64 = { asset_pattern = "git-interactive-rebase-tool-*-ubuntu-*_amd64.deb" }
linux-arm64 = { asset_pattern = "git-interactive-rebase-tool-*-ubuntu-*_arm64.deb" }
