[".cache/nushell/default_env.nu"]
type = "file"
url = "https://raw.githubusercontent.com/nushell/nushell/0.84.0/crates/nu-utils/src/sample_config/default_env.nu"

[".cache/nushell/default_config.nu"]
type = "file"
url = "https://raw.githubusercontent.com/nushell/nushell/0.84.0/crates/nu-utils/src/sample_config/default_config.nu"
