[".config/nushell/default_env.nu"]
type = "file"
url = "https://raw.githubusercontent.com/nushell/nushell/0.91.0/crates/nu-utils/src/sample_config/default_env.nu"

[".config/nushell/default_config.nu"]
type = "file"
url = "https://raw.githubusercontent.com/nushell/nushell/0.91.0/crates/nu-utils/src/sample_config/default_config.nu"

[".config/git/alias"]
type = "file"
url = "https://raw.githubusercontent.com/GitAlias/gitalias/main/gitalias.txt"
