#!/bin/bash -ex

### Trust github ###
#mkdir -p .ssh
#cat <<EOF >> .ssh/known_hosts
#|1|6WX8FDwncDK8tfyfkLLbvyepVRw=|15RHFpHg3GHML7eJqvNL/yVYChI= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
#|1|cccEMXs7ur0u/JXs4NQYv4A9Xb8=|Pddv+wa776NKeZ4v1yMn1cZWt4s= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
#EOF


# Install all the cool stuff

echo "This script will install all sorts of crazy (cool) stuff."

while true; do
    read -p "Do you wish to continue (Y/n)?" yn
        case $yn in
            [Yy]* ) break;;
            [Nn]* ) exit;;
            * ) echo "Please answer yes or no.";;
        esac
done

echo -e "\n"

# Create an alias for git and append it to .bashrc
echo "alias dotfiles='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'" >> ~/.bashrc 



# Install gitignore-boilerplates
# A shell script for easily accessing gitignore boilerplates from github.com/github/gitignore
# https://github.com/simonwhitaker/gitignore-boilerplates
#
echo -n "Installing gibo... "

# Get the bash completion file
curl https://raw.github.com/simonwhitaker/gitignore-boilerplates/master/gibo-completion.bash -so ~/.gibo-completion.bash

# Add gibo items to .bashrc and re-source it
echo "export PATH=$PATH:~/.bin" >> ~/.bashrc
echo "source ~/.gibo-completion.bash" >> ~/.bashrc

# Download gibo
mkdir -p ~/.bin
curl https://raw.github.com/simonwhitaker/gitignore-boilerplates/master/gibo -so ~/.bin/gibo

# Make sure gibo is executable
chmod +x ~/.bin/gibo
if [[ -x ~/.bin/gibo ]] ; then
    break
else
    set -e
fi

# Update gibo
gibo -u >/dev/null 2>/dev/null

# Check to see if it worked
if [[ $? != 0 ]] ; then
    echo "Not installed correctly!"
else
    echo "done."
fi



# Install Bash It
# https://github.com/revans/bash-it
#

echo -n "Installing Bash It... "
git clone http://github.com/revans/bash-it.git ~/.bash_it >/dev/null 2>/dev/null
echo "done."



# Install spf13-vim : Steve Francia's Vim Distribution
# https://github.com/spf13/spf13-vim
#
echo -n "Installing spf13-vim... "
curl http://j.mp/spf13-vim3 -L -o - >/dev/null 2>/dev/null | sh >/dev/null 2>/dev/null
echo "done."


# Install todo.txt
# https://github.com/ginatrapani/todo.txt-cli
#
echo -n "Installing todo.txt... "
mkdir -p ~/.todo
curl https://raw.github.com/ginatrapani/todo.txt-cli/master/todo.sh -so ~/.todo/todo.sh
curl https://raw.github.com/ginatrapani/todo.txt-cli/master/todo.cfg -so ~/.todo/todo.cfg
echo "source ~/.todo/todo.cfg" >> ~/.bashrc
echo "done."

echo -e "\n"
echo "All done."
echo "Make sure to type source ~/.bashrc"
