#!/usr/bin/env sh
#
#

### Setup user profile

# Switch to zsh shell
echo "Switch user shell to zsh"
#sudo usermod -s /bin/zsh jason


# Install freshshell
#
#

echo -n "Install freshshell... "

mkdir -p ~/.fresh/source/freshshell

if [ -d ~/.fresh/source/freshshell/fresh ]; then
  cd ~/.fresh/source/freshshell/fresh
  git pull --quiet --rebase >> /dev/null
else
  git clone --quiet https://github.com/freshshell/fresh ~/.fresh/source/freshshell/fresh
fi

echo "done."

echo "Freshen up files:"



cat << 'EOF' > ~/.freshrc


# freshshell.com
#
# Examples:
#
#   fresh twe4ked/dotfiles shell/functions.sh
#   fresh jasoncodes/dotfiles aliases/rails.sh
#   fresh jasoncodes/dotfiles config/tmux.conf --file
#
# See http://freshshell.com/readme for documentation.

# Not sure what is going on with the * selector on directories, could be a bug
# So for now this is more verbose than it ideally would be and uses direct
# file linking, which probably isnt the best either.


#FRESH_NO_BIN_CHECK=true

# Install fresh into its default location (this is where the install script places it,
# but then symlinks to it. Instead of doing this I am using an alias to the bin file).
fresh freshshell/fresh bin/fresh --bin=~/.fresh/bin/fresh

# Bring in all of my personal dotfiles
fresh jmorganson/dotfiles '*' --file

# Antigen (zsh plugin manager)
fresh zsh-users/antigen antigen.zsh --file=~/.antigen/antigen.zsh

# Vundle (vim plugin manager)
fresh gmarik/vundle autoload/vundle.vim --file=~/.vim/bundle/vundle/autoload/vundle.vim
fresh gmarik/vundle autoload/vundle/config.vim --file=~/.vim/bundle/vundle/autoload/vundle/config.vim
fresh gmarik/vundle autoload/vundle/installer.vim --file=~/.vim/bundle/vundle/autoload/vundle/installer.vim
fresh gmarik/vundle autoload/vundle/scripts.vim --file=~/.vim/bundle/vundle/autoload/vundle/scripts.vim

# SPF13-VIM
fresh spf13/spf13-vim .vimrc --file=~/.vimrc
fresh spf13/spf13-vim .vimrc.bundles --file=~/.vimrc.bundles


EOF


~/.fresh/source/freshshell/fresh/bin/fresh

