[".config/nushell/default_env.nu"]
type = "file"
url = "https://raw.githubusercontent.com/nushell/nushell/0.92.2/crates/nu-utils/src/sample_config/default_env.nu"

[".config/nushell/default_config.nu"]
type = "file"
url = "https://raw.githubusercontent.com/nushell/nushell/0.92.2/crates/nu-utils/src/sample_config/default_config.nu"

[".config/nushell/scripts/nu_scripts"]
type = "git-repo"
url = "https://github.com/nushell/nu_scripts.git"

[".config/git/alias"]
type = "file"
url = "https://raw.githubusercontent.com/GitAlias/gitalias/main/gitalias.txt"
