[misc]

# Commands to run after anything
[post_commands]
"Update brew bundle" = "/opt/homebrew/bin/brew bundle dump --force --file /Users/jasonmorganson/Library/Mobile Documents/com~apple~CloudDocs/Homebrew/Brewfile"
