[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[language-server.vscode-css-language-server.config]
css = { validate = { enable = true } }
scss = { validate = { enable = true } }
less = { validate = { enable = true } }
provideFormatter = true

[[language]]
name = "yaml"
formatter = { command = 'prettier', args = ["--parser", "yaml"] }

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true
completion = true
keyOrdering = false
schemaStore = { enable = true }
editor = { formatOnType = true }

[[language]]
name = "toml"
formatter = { command = 'dprint fmt' }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[language-server.vscode-json-language-server.config]
json = { validate = { enable = true }, format = { enable = true } }
provideFormatter = true

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "javascript"] }

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--stdin-filepath", "file.tsx"] }

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
formatter = { command = "ruff", args = ["format", "--quiet", "-"] }

[language-server.ruff]
command = "ruff-lsp"
