[env]
# XDG
XDG_CACHE_HOME = "{{ xdg_cache_home }}"
XDG_CONFIG_HOME = "{{ xdg_config_home }}"
XDG_BIN_HOME = "{{ env.HOME }}/.local/bin"
XDG_DATA_HOME = "{{ xdg_data_home }}"
XDG_STATE_HOME = "{{ xdg_state_home }}"

ACKRC = "{{ xdg_config_home }}/ack/ackrc"
ATOM_HOME = "{{ xdg_config_home }}/atom"
AWS_CONFIG_FILE = "{{ xdg_config_home }}/aws/config"
AWS_SHARED_CREDENTIALS_FILE = "{{ xdg_config_home }}/aws/credentials"
BASH_COMPLETION_USER_FILE = "{{ xdg_config_home }}/bash/completion/bash_completion"
BUNDLE_USER_CACHE = "{{ xdg_cache_home }}/bundle"
BUNDLE_USER_CONFIG = "{{ xdg_config_home }}/bundle"
BUNDLE_USER_PLUGIN = "{{ xdg_data_home }}/bundle"
CABAL_CONFIG = "{{ xdg_config_home }}/cabal/config"
CABAL_DIR = "{{ xdg_cache_home }}/cabal"
CARGO_HOME = "{{ xdg_data_home }}/cargo"
CCACHE_DIR = "{{ xdg_cache_home }}/cache"
CQL_HISTORY = "{{ xdg_cache_home }}/cassandra/cqlsh_history"
CRAWL_DIR = "{{ xdg_data_home }}/crawl"
CURSOR_CONFIG_DIR = "{{ xdg_config_home }}/cursor"
CUDA_CACHE_PATH = "{{ xdg_cache_home }}/nv"
DENO_DIR = "{{ xdg_cache_home }}/deno"
DOCKER_CONFIG = "{{ xdg_config_home }}/docker"
ELECTRUMDIR = "{{ xdg_data_home }}/electrum"
ELINKS_CONFDIR = "{{ xdg_config_home }}/elinks"
DOTNET_CLI_HOME = "{{ xdg_data_home }}/dotnet"
GEM_HOME = "{{ xdg_data_home }}/gem"
GEM_SPEC_CACHE = "{{ xdg_cache_home }}/gem"
GNUPGHOME = "{{ xdg_data_home }}/gnupg"
GOPATH = "{{ xdg_data_home }}/go"
GRADLE_USER_HOME = "{{ xdg_data_home }}/gradle"
GTK2_RC_FILES = "{{ xdg_config_home }}/gtk/2.0/gtkrc"
GTK_RC_FILES = "{{ xdg_config_home }}/gtk/1.0/gtkrc"
HISTFILE = "{{ xdg_cache_home }}/bash/history"
IMAPFILTER_HOME = "{{ xdg_config_home }}/imapfilter"
INPUTRC = "{{ xdg_config_home }}/readline/inputrc"
K9SCONFIG = "{{ xdg_config_home }}/k9s"
KDEHOME = "{{ xdg_config_home }}/kde"
KUBECONFIG = "{{ xdg_config_home }}/kube/config"
LEDGER_FILE = "{{ xdg_data_home }}/hledger/journal"
LEIN_HOME = "{{ xdg_data_home }}/lein"
LESSHISTFILE = "{{ xdg_cache_home }}/less/history"
LESSKEY = "{{ xdg_config_home }}/less/lesskey"
LS_COLORS = { value = "{{ exec(command='vivid --color-mode 8-bit generate one-dark', cache_key='ls-colors-' ~ tools.vivid.version ~ '-one-dark-8bit', cache_duration='52w') }}", tools = true }
MATHEMATICA_USERBASE = "{{ xdg_config_home }}/mathematica"
MAXIMA_USERDIR = "{{ xdg_config_home }}/maxima"
MEDNAFEN_HOME = "{{ xdg_config_home }}/mednafen"
MINIKUBE_HOME = "{{ xdg_data_home }}/minikube"
MOST_INITFILE = "{{ xdg_config_home }}/most/mostrc"
MPLAYER_HOME = "{{ xdg_config_home }}/mplayer"
MPLCONFIGDIR = "{{ xdg_config_home }}/matplotlib"
MYCLI_HISTFILE = "{{ xdg_data_home }}/mycli/history"
MYSQL_HISTFILE = "{{ xdg_data_home }}/sql_history"
NODE_REPL_HISTORY = "{{ xdg_cache_home }}/node_repl_history"
NPM_CONFIG_USERCONFIG = "{{ xdg_config_home }}/npm/npmrc"
NPM_CONFIG_PREFIX = "{{ xdg_data_home }}/npm"
NPM_CONFIG_CACHE = "{{ xdg_cache_home }}/npm"
NPM_CONFIG_LOGS_DIR = "{{ xdg_state_home }}/npm/logs"
NVM_DIR = "{{ xdg_data_home }}/nvm"
OPAMROOT = "{{ xdg_data_home }}/opam"
PARALLEL_HOME = "{{ xdg_config_home }}/parallel"
PASSWORD_STORE_DIR = "{{ xdg_data_home }}/pass"
PEX_ROOT = "{{ xdg_cache_home }}/pex"
PGPASSFILE = "{{ xdg_config_home }}/pg/pgpass"
PGSERVICEFILE = "{{ xdg_config_home }}/pg/pg_service.conf"
PIP_CACHE_DIR = "{{ xdg_cache_home }}/pip"
PSQLRC = "{{ xdg_config_home }}/pg/psqlrc"
PSQL_HISTORY = "{{ xdg_cache_home }}/psql_history"
PULUMI_HOME = "{{ xdg_data_home }}/pulumi"
PYLINTHOME = "{{ xdg_cache_home }}/pylint"
PYTHON_EGG_CACHE = "{{ xdg_cache_home }}/python-eggs"
PYTHON_HISTORY = "{{ xdg_state_home }}/python/history"
PYTHONPYCACHEPREFIX = "{{ xdg_cache_home }}/python/pycache"
PYTHONUSERBASE = "{{ xdg_data_home }}/python"
REDISCLI_HISTFILE = "{{ xdg_data_home }}/redis/rediscli_history"
REDISCLI_RCFILE = "{{ xdg_config_home }}/redis/redisclirc"
RENDER_CLI_CONFIG_PATH = "{{ xdg_config_home }}/render/cli.yaml"
RYE_HOME = "{{ xdg_data_home }}/rye"
RUSTUP_HOME = "{{ xdg_data_home }}/rustup"
SCREENRC = "{{ xdg_config_home }}/screen/screenrc"
SOLARGRAPH_CACHE = "{{ xdg_cache_home }}/solargraph"
STACK_ROOT = "{{ xdg_data_home }}/stack"
TASKDATA = "{{ xdg_data_home }}/task"
TASKRC = "{{ xdg_config_home }}/task/taskrc"
TS_NODE_HISTORY = "{{ xdg_state_home }}/ts_node_repl_history"
UNCRUSTIFY_CONFIG = "{{ xdg_config_home }}/uncrustify/uncrustify.cfg"
UNISON = "{{ xdg_data_home }}/unison"
WAKATIME_HOME = "{{ xdg_config_home }}/wakatime"
WEECHAT_HOME = "{{ xdg_config_home }}/weechat"
WGETRC = "{{ xdg_config_home }}/wgetrc"
XCOMPOSECACHE = "{{ xdg_cache_home }}/11/xcompose"
XCOMPOSEFILE = "{{ xdg_config_home }}/X11/xcompose"
__GL_SHADER_DISK_CACHE_PATH = "{{ xdg_cache_home }}/nv"
_Z_DATA = "{{ xdg_cache_home }}/z"
_.path = [
    "~/.orbstack/bin",
    "/Applications/Postgres.app/Contents/Versions/18/bin",
    "{{ env.XDG_BIN_HOME }}",
    "{{ env.NPM_CONFIG_PREFIX }}/bin",
    "{{ xdg_data_home }}/pnpm/bin",
    "{{ env.GOPATH }}/bin",
    "{{ env.CARGO_HOME }}/bin",
    "/home/linuxbrew/.linuxbrew/bin",
    "/home/linuxbrew/.linuxbrew/sbin",
    "/opt/homebrew/bin",
    "/opt/homebrew/sbin",
    "/usr/local/bin",
    "/usr/bin",
    "/usr/sbin",
    "/bin",
    "/sbin"
]


# HK
HK = "true"
HK_PKL_BACKEND = "pklr"
HK_STASH = "none"

# fnox
FNOX_SHELL_OUTPUT = "none"
FNOX_AGE_KEY_FILE = "~/.ssh/id_ed25519"

TERM = "xterm-256color"
TERMINFO = "{{ xdg_data_home }}/terminfo"
TERMINFO_DIRS = "{{ xdg_data_home }}/terminfo:/usr/share/terminfo"
