[aliases]

# chezmoi
dotfiles = "chezmoi"

# Habits
ag = "rg"
tig = "gitui"
vi = "hx"

# ls
l = "lsd"
ls = "lsd"
la = "lsd -a"
ll = "lsd -l"
lla = "lsd -la"

# git
g = "git"

# Python
py = "python"
pip = "python -m pip"

# Kube
k = "kubectl"
kns = "kubens"
kctx = "kubectx"
