[aliases]

# chezmoi
dotfiles = "chezmoi"

# Habits
ag = "rg"
tig = "gitui"
vi = "hx"

# ls
l = "lsd"
ls = "lsd"
la = "lsd --all"
ll = "lsd --long"
lt = "lsd --tree"

# git
g = "git"

# Pulumi
p = "pulumi"

# Python
py = "python"
pip = "python -m pip"

# Kube
k = "kubectl"
kns = "kubens"
kctx = "kubectx"

# Node
node = "node --experimental-transform-types"
