"$schema" = 'https://starship.rs/config-schema.json'

format = """
$all\
${custom.pkgx}$character
"""

[aws]
disabled = true

[gcloud]
disabled = true

[shell]
disabled = false
style = "bright-black"

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"

[git_branch]
symbol = "⎇ "

[cmd_duration]
disabled = true

[custom.pkgx]
shell = ['sh']
command = 'echo +$PKGX_POWDER'
when = '[ -n "$PKGX_POWDER" ] && echo "0"'
style = "bright-black"
