theme = "github_dark_256"

[editor]
auto-save = true
cursorline = true
line-number = "relative"

[editor.statusline]
center = ["diagnostics"]
right = ["selections", "register", "position", "file-type", "file-encoding"]

[editor.cursor-shape]
insert = "block"
normal = "underline"
select = "underline"

[editor.file-picker]
hidden = false

