theme = "theme"

[editor]
cursorline = true
line-number = "relative"

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "file-name", "read-only-indicator", "version-control", "spacer", "file-modification-indicator", "spacer", "spinner"]
center = ["diagnostics"]
right = ["selections", "register", "position", "file-type", "file-encoding"]
