theme = "theme"

[editor]
auto-save = true
cursorline = true
line-number = "relative"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "file-name", "read-only-indicator", "version-control", "spacer", "file-modification-indicator", "spacer", "spinner"]
center = ["diagnostics"]
right = ["selections", "register", "position", "file-type", "file-encoding"]

[keys.normal]
"esc" = ["collapse_selection", ":w"]

[keys.select]
"esc" = ["collapse_selection", "normal_mode", ":w"]

[keys.insert]
"esc" = ["normal_mode", ":w"]
