theme = "github_dark_256"

[editor]
auto-save = true
cursorline = true
line-number = "relative"

[editor.statusline]
center = ["diagnostics"]
right = ["version-control", "file-type", "file-encoding", "position-percentage", "position", "total-line-numbers"]

[editor.cursor-shape]
insert = "block"
normal = "underline"
select = "underline"

[editor.file-picker]
hidden = false

