name: Test install script

on: push

env:
  GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-11, macos-12]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: which sha256_checksum
        run: which sha256_checksum
