name: Test

on: pull_request

env:
  MISE_CONFIG_DIR: ${{ github.workspace }}/home/.config/mise
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USER: ${{ github.repository_owner }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - name: Run tests
        run: mise run test
